#244 refactored announcements => changed naming to reminders
MarkusKgit/MonkeyBot pull request #249
Opened 2021-10-05 15:28 UTC by AlexanderGipp

**This does not change any functionality and only changes the naming of the module.**

2021-10-05 16:13 UTC, MarkusKgit requested changes
This needs a database migration

2021-10-05 16:33 UTC, AlexanderGipp commented
> 
> 
> This needs a database migration

Opps i totally forgot, thank you for **reminding** me 😅

2021-10-05 18:19 UTC, MarkusKgit commented
No worries :-) But can we do a [rename](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migrationbuilder.renametable?view=efcore-5.0) instead of dropping the table?

2021-10-05 18:27 UTC, AlexanderGipp commented
> 
> 
> No worries :-) But can we do a [rename](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migrationbuilder.renametable?view=efcore-5.0) instead of dropping the table?

Oh damn you are pushing my ef core knowledge to its limit. Let me look into that though 😄

2021-10-05 18:30 UTC, AlexanderGipp commented
> 
> 
> No worries :-) But can we do a [rename](https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.migrations.migrationbuilder.renametable?view=efcore-5.0) instead of dropping the table?

Does this look solid to you?

```cs
 protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "Announcements",
                newName: "Reminder");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

            migrationBuilder.RenameTable(
                name: "Reminder",
                newName: "Announcements");
        }
```

2021-10-05 18:38 UTC, MarkusKgit commented
To be honest I never had to manually touch the migrations before ;-) Looks good but I think since you renamed some columns to the correct casing (ID -> Id) it will need a couple of column renames as well. 
```cs
migrationBuilder.RenameColumn(
                name: "ID",
                table: "Reminder",
                newName: "Id");
```

But if it turns out to be too much hassle we can leave it as is. I have no pending reminders in my db instance. However I don't know if anyone else is actively using the Bot and might have some :-)

2021-10-05 18:40 UTC, AlexanderGipp commented
> 
> 
> To be honest I never had to manually touch the migrations before ;-) Looks good but I think since you renamed some columns to the correct casing (ID -> Id) it will need a couple of column renames as well.
> 
> ```cs
> migrationBuilder.RenameColumn(
>                 name: "ID",
>                 table: "Reminder",
>                 newName: "Id");
> ```
> 
> But if it turns out to be too much hassle we can leave it as is. I have no pending reminders in my db instance. However I don't know if anyone else is actively using the Bot and might have some :-)

I will glady change it, however you will need to test those changes and make sure everything still works as expected.
Just let me know if i should contiue with the migration script thingy :)

2021-10-05 18:41 UTC, MarkusKgit commented
Sure, if you push the changes I can set up my testing Bot with actual values in the DB and try it out

2021-10-05 19:47 UTC, MarkusKgit requested changes

2021-10-05 19:47 UTC, MarkusKgit commented on MonkeyBot/Migrations/20211005163642_UpdatedReminders.cs
> +                table: "Reminder",
table name should be Announcements here or the RenameTable needs to be the last step.

2021-10-05 19:47 UTC, MarkusKgit commented on MonkeyBot/Database/MonkeyDBContext.cs
> +        public DbSet<Reminder> Reminder { get; set; }
Can we please pluralize this, so it is consistent with the others? (`Reminder` -> `Reminders`)

2021-10-05 19:47 UTC, MarkusKgit commented on MonkeyBot/Migrations/20211005163642_UpdatedReminders.cs
> +                newName: "Reminder");
Pluralize table name Reminders

2021-10-06 04:25 UTC, MarkusKgit approved these changes

2021-10-06 04:26 UTC, MarkusKgit commented
Everything mint now, thank you very much

2021-10-06 04:26 UTC, merged